server:
  port: 8083
spring:
  application:
    name: feign-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

#开启feign自带hisrtrix
feign:
  hystrix:
    enabled: true