server:
  port: 8092

spring:
  application:
    name: zipkin-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false